# Generated by Django 2.2.2 on 2019-06-09 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('pub_date', models.DateField()),
                ('added_date', models.DateField()),
                ('rating', models.IntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklists.Source')),
            ],
        ),
    ]
